name: EmeraldFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the Emerald Freedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials]
author: [DUFC_Liam]
authors: [Madgeek1450, Prozza]

# plugin.yml is no longer used to define commands.
